backend = "glx";
vsync = true;
fading = false;
blur: {
  method = "dual_kawase";
  strength = 1;
  background = true;
  background-frame = false;
  background-fixed = false;
}
blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c"
];

shadow-exclude = [
  "class_g = 'Rofi'",
];
